package org.telescope.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a {@link Record} as the target of a compile-time bean bridge generated by the {@code
 * telescope-codegen} annotation processor. The annotation names the POJO to convert to and from;
 * the processor emits a sibling class {@code <RecordName>Bridge} holding a {@code public static
 * final Telescope<Pojo, Record>} constant.
 *
 * <p>This is the reflection-free, compile-checked counterpart to the runtime {@link
 * org.telescope.Telescope#fromBean(Class)}. The processor builds {@code BRIDGE} from the public
 * {@code Telescope.from(Pojo.class).to(Record.class).using(forward, backward)} factory, where the
 * two lambdas it emits call the POJO's public members directly. There is no runtime reflection, no
 * {@code java.desktop} dependency, and no {@code setAccessible}; a missing getter or mismatched
 * component is a compile error rather than a runtime failure.
 *
 * <p>The POJO {@code ->} record direction reads public getters ({@code getX()}, or {@code isX()}
 * for booleans). The record {@code ->} POJO direction picks one construction strategy,
 * auto-detected at compile time in this priority order:
 *
 * <ol>
 *   <li>a public all-args constructor (parameters in record-component order),
 *   <li>a static {@code builder()} whose builder exposes a per-component method ({@code x}, {@code
 *       setX}, or {@code withX}) and a {@code build()},
 *   <li>a public no-arg constructor plus a {@code setX} setter per component.
 * </ol>
 *
 * <p>Annotate the record (which you own) rather than the POJO, since the POJO is often a generated
 * or third-party class you cannot modify. Records only, and only top-level records — the generated
 * top-level {@code *Bridge} class cannot reference a nested record's canonical constructor.
 *
 * <pre>{@code
 * // Gradle:
 * annotationProcessor("io.github.eschizoid:telescope-codegen:0.1.0")
 *
 * // Source — the record points at the POJO:
 * @BeanBridge(LegacyUser.class)
 * record UserRecord(String id, String email, String name) {}
 *
 * // Generated alongside (UserRecordBridge.java):
 * // public final class UserRecordBridge {
 * //   public static final Telescope<LegacyUser, UserRecord> BRIDGE =
 * //     Telescope.from(LegacyUser.class).to(UserRecord.class).using(
 * //       p -> new UserRecord(p.getId(), p.getEmail(), p.getName()),
 * //       r -> new LegacyUser(r.id(), r.email(), r.name()));   // strategy auto-detected
 * // }
 *
 * // Usage — convert a POJO to the record, or vice versa:
 * final var record = UserRecordBridge.BRIDGE.read(legacyUser);
 * final var bean   = UserRecordBridge.BRIDGE.set(legacyUser, record);
 *
 * // BRIDGE is a Telescope value, so it composes as a navigation step:
 * final var lowered = Telescope.of(Page.class)
 *     .each(Page::users)              // each LegacyUser on the page
 *     .then(UserRecordBridge.BRIDGE)  // view it as a UserRecord
 *     .field(UserRecord::email)
 *     .update(page, String::toLowerCase);
 * }</pre>
 *
 * @see org.telescope.Telescope#fromBean(Class)
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)
public @interface BeanBridge {
  /**
   * The POJO type this record bridges to and from. Must be a class type with a getter per record
   * component and one of the supported construction strategies.
   */
  Class<?> value();
}
