package io.github.eschizoid.telescope.demo.spring.bughunt.bridge;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Sibling demo for {@code @Bridge}: walks {@link InvoiceLine} into {@link InvoiceLineEntity} via
 * the codegen-emitted {@code InvoiceLinePath.start().asInvoiceLineEntity()} hop and back.
 *
 * <p>No JPA — this is a plain HTTP endpoint that exists to prove the {@code @Bridge}-generated
 * navigator hop compiles and runs end-to-end on the demo's real Spring context. The bridge itself
 * does the conversion; the controller just exposes both directions.
 */
@RestController
@RequestMapping("/bughunt/invoice-bridge")
public class InvoiceBridgeController {

  @PostMapping("/forward")
  public ResponseEntity<InvoiceLineEntity> forward(@RequestBody final InvoiceLine line) {
    // Compile-time-bound: `asInvoiceLineEntity()` is generated by BridgeProcessor on the source
    // Path navigator. Because InvoiceLineEntity is @BeanFocus-navigable, the hop returns
    // InvoiceLineEntityPath<InvoiceLine>; `.read(line)` runs the underlying Telescope through
    // the BRIDGE Iso and materialises the entity.
    final var entity = InvoiceLinePath.start().asInvoiceLineEntity().read(line);
    return ResponseEntity.ok(entity);
  }

  @PostMapping("/backward")
  public ResponseEntity<InvoiceLine> backward(@RequestBody final InvoiceLineEntity entity) {
    // The generated bridge class exposes static `forward(Source)` / `backward(Target)` methods
    // alongside its `BRIDGE` Telescope constant. Both are usable; we lean on `backward` here.
    return ResponseEntity.ok(InvoiceLineBridge.backward(entity));
  }
}
