package io.github.eschizoid.telescope.demo.invoicing.api;

import io.github.eschizoid.telescope.demo.invoicing.domain.InvoiceHeader;
import io.github.eschizoid.telescope.demo.invoicing.domain.InvoiceHeaderBridge;
import io.github.eschizoid.telescope.demo.invoicing.domain.InvoiceLine;
import io.github.eschizoid.telescope.demo.invoicing.domain.InvoiceLineBridge;
import io.github.eschizoid.telescope.demo.invoicing.domain.InvoiceLineTelescope;
import io.github.eschizoid.telescope.demo.invoicing.persistence.InvoiceHeaderEntity;
import io.github.eschizoid.telescope.demo.invoicing.persistence.InvoiceLineEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * HTTP demo of {@code @Bridge}-emitted record↔bean conversion. Two endpoint pairs:
 *
 * <ul>
 *   <li>{@code POST /invoices/lines/forward} and {@code /lines/backward} — drive the bridge on a
 *       single {@code InvoiceLine}. Demonstrates the {@code asInvoiceLineEntity()} navigator hop
 *       generated by {@code BridgeProcessor} on the source Path.
 *   <li>{@code POST /invoices/headers/forward} and {@code /headers/backward} — drive the deep
 *       bridge on a header carrying {@code List<InvoiceLine>}. {@code InvoiceHeaderBridge}
 *       auto-recurses into the user-declared {@code InvoiceLineBridge} for every list element — no
 *       manual list-lift wiring at this call site.
 * </ul>
 *
 * <p>The controller itself does no conversion work; the generated bridge classes own that. Each
 * endpoint is a one-liner that proves the codegen path compiles and runs in a real Spring context.
 */
@RestController
@RequestMapping("/invoices")
public class InvoiceBridgeController {

  /**
   * Demonstrates the {@code InvoiceLineTelescope.focus().asInvoiceLineEntity()} navigator hop.
   * {@code BridgeProcessor} generated the {@code asInvoiceLineEntity()} method on the source Path;
   * because {@code InvoiceLineEntity} is {@code @BeanFocus}-navigable, the hop returns {@code
   * InvoiceLineEntityPath<InvoiceLine>} and {@code .read(line)} runs the underlying Telescope
   * through the {@code BRIDGE} Iso to materialise the entity.
   */
  @PostMapping("/lines/forward")
  public ResponseEntity<InvoiceLineEntity> lineForward(@RequestBody final InvoiceLine line) {
    final var entity = InvoiceLineTelescope.focus().asInvoiceLineEntity().read(line);
    return ResponseEntity.ok(entity);
  }

  /**
   * The generated bridge class exposes static {@code forward(Source)} / {@code backward(Target)}
   * methods alongside its {@code BRIDGE} Telescope constant. Both forms are usable; this endpoint
   * uses {@code backward(...)} directly.
   */
  @PostMapping("/lines/backward")
  public ResponseEntity<InvoiceLine> lineBackward(@RequestBody final InvoiceLineEntity entity) {
    return ResponseEntity.ok(InvoiceLineBridge.backward(entity));
  }

  /**
   * Deep bridge demonstration: {@code InvoiceHeader} carries a {@code List<InvoiceLine>}. The
   * generated {@code InvoiceHeaderBridge} list-lifts automatically and delegates per-element
   * conversion to the user-declared {@code InvoiceLineBridge}. No manual ceremony.
   */
  @PostMapping("/headers/forward")
  public ResponseEntity<InvoiceHeaderEntity> headerForward(@RequestBody final InvoiceHeader header) {
    return ResponseEntity.ok(InvoiceHeaderBridge.forward(header));
  }

  @PostMapping("/headers/backward")
  public ResponseEntity<InvoiceHeader> headerBackward(@RequestBody final InvoiceHeaderEntity entity) {
    return ResponseEntity.ok(InvoiceHeaderBridge.backward(entity));
  }
}
