package io.github.eschizoid.telescope.conversion;

import io.github.eschizoid.telescope.internal.pairing.Allocation;
import io.github.eschizoid.telescope.internal.pairing.ContainerAllocation;
import io.github.eschizoid.telescope.internal.pairing.ReflectionProps;
import java.lang.reflect.Type;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.HashSet;
import java.util.IdentityHashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.PriorityQueue;
import java.util.Set;
import java.util.SortedMap;
import java.util.SortedSet;
import java.util.Stack;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.Vector;
import java.util.WeakHashMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentSkipListMap;
import java.util.concurrent.ConcurrentSkipListSet;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.CopyOnWriteArraySet;
import java.util.concurrent.PriorityBlockingQueue;
import java.util.function.Function;

/**
 * The shallow copy a conversion makes of a container whose declared type is the same on both sides.
 * {@code Telescope.mapper(...)} makes it for such a component, and a bridge generated by
 * {@code @Bridge} calls it, so the two paths copy the same way.
 *
 * <p>The copy behaves like the source and never instantiates a class telescope does not know: a JDK
 * collection is copied into its own class, anything else into the nearest JDK class that keeps its
 * ordering, and failing that into the declared type's default. Unmodifiable inputs are returned as
 * they are. The elements, and a map's keys and values, are the source's own.
 *
 * <p>Public so generated code in any package can call it; not meant to be called directly.
 */
public final class ContainerCopy {

  private ContainerCopy() {}

  /**
   * A shallow copy of {@code source}, or {@code source} itself when it is null or unmodifiable.
   *
   * @param source the container to copy
   * @param declared the type the container is declared as on both sides
   * @param <C> the container's type
   * @return the copy
   */
  @SuppressWarnings({ "unchecked", "rawtypes" })
  public static <C> C of(final C source, final Class<?> declared) {
    if (source == null || UNMODIFIABLE.contains(source.getClass())) return source;
    final var own = OWN_CLASS_COPIES.get(source.getClass());
    if (own != NO_COPY) return (C) own.apply(source);
    // An ordering the class cannot be rebuilt with is kept by the JDK class that carries one, where
    // the declared type can hold it.
    if (source instanceof SortedSet sorted && declared.isAssignableFrom(TreeSet.class)) {
      return (C) new TreeSet<>(sorted);
    }
    if (source instanceof SortedMap sorted && declared.isAssignableFrom(TreeMap.class)) {
      return (C) new TreeMap<>(sorted);
    }
    if (source instanceof PriorityQueue queue && declared.isAssignableFrom(PriorityQueue.class)) {
      return (C) new PriorityQueue<>(queue);
    }
    return (C) DECLARED_COPIES.get(declared).apply(source);
  }

  /** Marks a runtime class with no copy into itself. */
  private static final Function<Object, Object> NO_COPY = input -> {
    throw new IllegalStateException("no copy for " + input.getClass().getName());
  };

  /**
   * The JDK containers whose copy constructor builds an equal container of the same class, keeping
   * the comparator of a sorted one. They are named rather than probed, so no constructor is looked
   * up at run time, and a copy constructor takes the source's elements in one step. Every class the
   * shared allocation table rebuilds a declared type as is among them, which is what the fallback
   * for a declared type relies on.
   */
  @SuppressWarnings({ "unchecked", "rawtypes" })
  private static final Map<Class<?>, Function<Object, Object>> COPY_CONSTRUCTORS = Map.ofEntries(
    Map.entry(ArrayList.class, input -> new ArrayList<>((Collection) input)),
    Map.entry(LinkedList.class, input -> new LinkedList<>((Collection) input)),
    Map.entry(ArrayDeque.class, input -> new ArrayDeque<>((Collection) input)),
    Map.entry(Vector.class, input -> new Vector<>((Collection) input)),
    Map.entry(Stack.class, input -> {
      final var stack = new Stack<>();
      stack.addAll((Collection) input);
      return stack;
    }),
    Map.entry(CopyOnWriteArrayList.class, input -> new CopyOnWriteArrayList<>((Collection) input)),
    Map.entry(CopyOnWriteArraySet.class, input -> new CopyOnWriteArraySet<>((Collection) input)),
    Map.entry(PriorityQueue.class, input -> new PriorityQueue<>((PriorityQueue) input)),
    Map.entry(PriorityBlockingQueue.class, input -> new PriorityBlockingQueue<>((PriorityBlockingQueue) input)),
    Map.entry(HashSet.class, input -> new HashSet<>((Collection) input)),
    Map.entry(LinkedHashSet.class, input -> new LinkedHashSet<>((Collection) input)),
    Map.entry(TreeSet.class, input -> new TreeSet<>((SortedSet) input)),
    Map.entry(ConcurrentSkipListSet.class, input -> new ConcurrentSkipListSet<>((SortedSet) input)),
    Map.entry(HashMap.class, input -> new HashMap<>((Map) input)),
    Map.entry(LinkedHashMap.class, input -> new LinkedHashMap<>((Map) input)),
    Map.entry(TreeMap.class, input -> new TreeMap<>((SortedMap) input)),
    Map.entry(ConcurrentSkipListMap.class, input -> new ConcurrentSkipListMap<>((SortedMap) input)),
    Map.entry(ConcurrentHashMap.class, input -> new ConcurrentHashMap<>((Map) input)),
    Map.entry(IdentityHashMap.class, input -> new IdentityHashMap<>((Map) input)),
    Map.entry(WeakHashMap.class, input -> new WeakHashMap<>((Map) input)),
    Map.entry(EnumMap.class, input -> new EnumMap<>((EnumMap) input))
  );

  /** How a container of each runtime class is copied into its own class, or {@link #NO_COPY}. */
  private static final ClassValue<Function<Object, Object>> OWN_CLASS_COPIES = new ClassValue<>() {
    @Override
    @SuppressWarnings({ "unchecked", "rawtypes" })
    protected Function<Object, Object> computeValue(final Class<?> type) {
      final var named = COPY_CONSTRUCTORS.get(type);
      if (named != null) return named;
      // EnumSet's implementations are private to java.util; clone is how the JDK copies one.
      if (EnumSet.class.isAssignableFrom(type)) return input -> ((EnumSet) input).clone();
      return NO_COPY;
    }
  };

  /**
   * The shared allocation rules, over reflection handles, which say what a declared type is rebuilt
   * as: the class the table names, or the family default standing in for an interface or abstract
   * type it does not.
   */
  private static final ContainerAllocation<Type> ALLOCATION = new ContainerAllocation<>(new ReflectionProps());

  /**
   * How a container is copied into the class the shared allocation rules rebuild a declared type
   * as.
   */
  private static final ClassValue<Function<Object, Object>> DECLARED_COPIES = new ClassValue<>() {
    @Override
    protected Function<Object, Object> computeValue(final Class<?> declared) {
      final var kind = ALLOCATION.familyOf(declared);
      if (ALLOCATION.implementationFor(declared, kind) instanceof Allocation.Build build) {
        for (final var entry : COPY_CONSTRUCTORS.entrySet()) {
          if (entry.getKey().getName().equals(build.implName())) return entry.getValue();
        }
      }
      throw new IllegalStateException("telescope rebuilds no copy of " + declared.getName());
    }
  };

  /**
   * The classes of the JDK's unmodifiable containers, read off instances of each: the {@code
   * List.of}, {@code Set.of} and {@code Map.of} families, and the {@code Collections} singletons,
   * empties and unmodifiable views. They are private classes, so an instance is the only way to
   * name one.
   */
  private static final Set<Class<?>> UNMODIFIABLE = Set.copyOf(
    List.of(
      List.of().getClass(),
      List.of(1).getClass(),
      List.of(1, 2, 3).getClass(),
      List.of(1, 2, 3).subList(0, 1).getClass(),
      Set.of().getClass(),
      Set.of(1).getClass(),
      Set.of(1, 2, 3).getClass(),
      Map.of().getClass(),
      Map.of(1, 1).getClass(),
      Map.of(1, 1, 2, 2).getClass(),
      Collections.emptyList().getClass(),
      Collections.emptySet().getClass(),
      Collections.emptySortedSet().getClass(),
      Collections.emptyNavigableSet().getClass(),
      Collections.emptyMap().getClass(),
      Collections.emptySortedMap().getClass(),
      Collections.emptyNavigableMap().getClass(),
      Collections.singletonList(1).getClass(),
      Collections.singleton(1).getClass(),
      Collections.singletonMap(1, 1).getClass(),
      Collections.unmodifiableCollection(new ArrayList<>()).getClass(),
      Collections.unmodifiableSequencedCollection(new ArrayList<>()).getClass(),
      Collections.unmodifiableList(new ArrayList<>()).getClass(),
      Collections.unmodifiableList(new LinkedList<>()).getClass(),
      Collections.unmodifiableSet(new HashSet<>()).getClass(),
      Collections.unmodifiableSequencedSet(new LinkedHashSet<>()).getClass(),
      Collections.unmodifiableSortedSet(new TreeSet<>()).getClass(),
      Collections.unmodifiableNavigableSet(new TreeSet<>()).getClass(),
      Collections.unmodifiableMap(new HashMap<>()).getClass(),
      Collections.unmodifiableSequencedMap(new LinkedHashMap<>()).getClass(),
      Collections.unmodifiableSortedMap(new TreeMap<>()).getClass(),
      Collections.unmodifiableNavigableMap(new TreeMap<>()).getClass()
    )
  );
}
