package io.github.eschizoid.telescope.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Repeatable;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a record or class as the <em>source</em> of a compile-time, reflection-free bidirectional
 * bridge to the type named by {@link #value()}. The {@code telescope-codegen} processor emits a
 * sibling class {@code <Source>Bridge} holding a {@code public static final Telescope<Source,
 * Target> BRIDGE}.
 *
 * <p>Both sides may be records or JavaBeans-style POJOs, in any combination (record&harr;record,
 * record&harr;POJO, POJO&harr;POJO). Fields are matched by name and the mapping is a
 * <strong>bijection</strong> — each side must expose the same set of field names (so a round-trip
 * is lossless). The generated forward/backward lambdas call public members directly: there is no
 * runtime reflection, no {@code java.desktop}, and no {@code setAccessible}; a name mismatch or a
 * missing construction strategy is a compile error rather than a runtime failure.
 *
 * <p>Each direction reads the other side's fields (a record component {@code x()}, or a POJO getter
 * {@code getX()} / {@code isX()}) and rebuilds, auto-detecting a construction strategy at compile
 * time: a record uses its canonical constructor; a POJO uses, in priority order, a public
 * constructor whose parameter names match the fields, then a static {@code builder()}, then a
 * public no-arg constructor plus {@code setX} setters.
 *
 * <p>Annotate whichever side you own. Records and classes only, and only top-level types on both
 * sides — the generated top-level {@code *Bridge} class cannot name a nested type's constructor.
 *
 * <p>This is the reflection-free, compile-checked counterpart to the runtime {@link
 * io.github.eschizoid.telescope.Telescope#map(Class, Class,
 * io.github.eschizoid.telescope.mapping.MapStep...)} — that single factory handles record↔record,
 * POJO↔POJO, and POJO↔record at any depth. For renames or per-field transforms (which can't be
 * expressed in an annotation), use the runtime form instead.
 *
 * <pre>{@code
 * // Source — the entity points at the DTO it bridges to:
 * @Bridge(UserDto.class)
 * record UserEntity(String id, String email) {}
 *
 * // Generated alongside (UserEntityBridge.java):
 * // public final class UserEntityBridge {
 * //   public static final Telescope<UserEntity, UserDto> BRIDGE =
 * //     Telescope.from(UserEntity.class).to(UserDto.class).using(
 * //       s -> new UserDto(s.id(), s.email()),
 * //       t -> new UserEntity(t.id(), t.email()));   // strategy auto-detected per side
 * // }
 *
 * UserDto dto = UserEntityBridge.BRIDGE.read(entity);
 * }</pre>
 *
 * @see io.github.eschizoid.telescope.Telescope#map(Class, Class,
 *     io.github.eschizoid.telescope.mapping.MapStep...)
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)
@Repeatable(Bridges.class)
public @interface Bridge {
  /**
   * Model-anchored target. Required when the annotation sits on the source type itself:
   * {@code @Bridge(UserDto.class) record UserEntity(...)}. Defaults to {@link Void} so that the
   * carrier-class form ({@link #source()} + {@link #target()}, where the annotation sits on a third
   * class that names both sides) can omit it.
   */
  Class<?> value() default Void.class;

  /**
   * Carrier-form source — the type the generated {@code BRIDGE} reads from. Set this (plus {@link
   * #target()}) when the annotation cannot live on the source itself because source and target live
   * in modules with no compile-time visibility to one another. The carrier class declared by
   * {@code @Bridge(source = X.class, target = Y.class)} carries no behaviour; it exists only to
   * declare the pair. The generated {@code <Carrier>Bridge} class is emitted in the carrier's
   * package, NOT in the source's package (the carrier's module is the only one that sees both
   * sides).
   *
   * <p>When {@code source} is left at its default ({@code Void.class}), the model-anchored form is
   * used: the annotated element IS the source, and the target comes from {@link #value()}.
   *
   * <p>The {@code as<Target>()} Path hop generated by {@code @Focus} / {@code @BeanFocus} is only
   * emitted for the model-anchored form — carrier bridges have no source-side {@code <Source>Path}
   * to attach the hop to. Adopters reference {@code <Carrier>Bridge.BRIDGE} directly via {@code
   * Telescope.from(...).to(...).using(BRIDGE)} or {@code Telescope.of(Source.class) .then(BRIDGE)}.
   *
   * @see #target()
   */
  Class<?> source() default Void.class;

  /**
   * Carrier-form target — the type the generated {@code BRIDGE} writes to. Paired with {@link
   * #source()}. Required when {@code source} is set; ignored otherwise (the model-anchored form
   * uses {@link #value()} for the target).
   *
   * @see #source()
   */
  Class<?> target() default Void.class;

  /**
   * Source field names that exist on the annotated source but not on the target. Forward conversion
   * skips them; backward conversion fills the dropped slot with {@code null} for reference types,
   * {@code 0} for numeric primitives, {@code false} for {@code boolean}, and {@code '\0'} (the NUL
   * character) for {@code char}. Use this when the source carries fields the target shape
   * legitimately doesn't (e.g. an internal-only field that the partner DTO does not carry).
   *
   * <p>Drops do not need a counterpart on the other side — they relax the strict-bijection check by
   * exactly the names listed. A drop name that is not actually present on the source is a compile
   * error.
   */
  String[] drops() default {};

  /**
   * Source-to-target name remappings — pairs whose source field name and target field name differ.
   * The bijection check considers a renamed source name and its mapped target name as matched. See
   * {@link Rename} for the per-pair shape.
   *
   * <pre>{@code
   * @Bridge(value = OrderEntity.class, renames = {
   *   @Rename(source = "orderNumber", target = "referenceCode")
   * })
   * }</pre>
   *
   * <p>Each rename's source must name a real field on the annotated source; each target must name a
   * real field on the bridge target. No two renames may share the same target. By default no two
   * renames may share the same source either; opt into forward-only fan-out by setting {@link
   * Rename#forwardOnly()} on all conflicting renames — backward then reads from the first declared
   * fan-out target. The non-fan-out case stays a strict bijection within the rename set.
   */
  Rename[] renames() default {};

  /**
   * Per-field typed conversions — for cases where the two sides name compatible fields but the
   * types differ (e.g. {@code BigDecimal} on the source, {@code long} on the target). Each {@link
   * Transform} names a source field and a {@link io.github.eschizoid.telescope.conversion.BridgeFn}
   * class whose {@code forward}/{@code backward} convert the value in each direction.
   *
   * <pre>{@code
   * @Bridge(value = LineItemEntity.class, transforms = {
   *   @Transform(field = "unitPrice", using = CentsConverter.class)
   * })
   * }</pre>
   *
   * <p>Each transform's field must be a real field on the annotated source. A field with a
   * transform is exempt from the same-type check that other fields go through; the transform's
   * input/output types are the bridge contract for that slot.
   */
  Transform[] transforms() default {};

  /**
   * Forward-only target-field literal injections. Each {@link Constant} names a target field that
   * doesn't exist on the source and a string literal value the emitted forward direction will set
   * on that field. The backward direction silently drops the slot — the source has no field to
   * reconstruct from.
   *
   * <pre>{@code
   * @Bridge(value = LineItemEntity.class, constants = {
   *   @Constant(field = "source", value = "API")
   * })
   * }</pre>
   *
   * <p>The named target field is exempt from the strict-bijection check. A target field listed in
   * {@code constants} may not also appear in {@link #computes()}, {@link #renames()}, or {@link
   * #drops()} for the same pair.
   */
  Constant[] constants() default {};

  /**
   * Forward-only target-field computed injections. Each {@link Compute} names a target field that
   * doesn't exist on the source and a {@link java.util.function.Supplier} class whose {@code get()}
   * the emitted forward direction will call to produce the value. The backward direction silently
   * drops the slot.
   *
   * <pre>{@code
   * @Bridge(value = LineItemEntity.class, computes = {
   *   @Compute(field = "createdAt", using = NowSupplier.class)
   * })
   * }</pre>
   *
   * <p>The named target field is exempt from the strict-bijection check. A target field listed in
   * {@code computes} may not also appear in {@link #constants()}, {@link #renames()}, or {@link
   * #drops()} for the same pair.
   */
  Compute[] computes() default {};

  /**
   * Null-coalescing default values for source fields. Each {@link Default} names a source field and
   * a fallback literal that the forward direction substitutes when the source value is {@code
   * null}. Mirrors MapStruct's {@code @Mapping(defaultValue = …)} and the runtime {@link
   * io.github.eschizoid.telescope.mapping.Mapping#toOrElse(
   * io.github.eschizoid.telescope.Telescope.Accessor,
   * io.github.eschizoid.telescope.Telescope.Accessor, Object) Mapping.toOrElse(srcAcc, tgtAcc,
   * defaultValue)} factory.
   *
   * <pre>{@code
   * @Bridge(value = UserEntity.class, defaults = {
   *   @Default(field = "region", value = "EMEA")
   * })
   * public record User(String id, String region) {}
   * }</pre>
   *
   * <p>Backward direction is identity — the substituted default round-trips back to the source slot
   * as itself. A field listed in {@code defaults} cannot also appear in {@link #drops()} for this
   * pair (the two mechanisms have incompatible semantics).
   */
  Default[] defaults() default {};

  /**
   * Per-field nested-bridge overrides. Each {@link ViaMapper} names a source field and a bridge
   * class to delegate to — escape hatch when the auto-recursion can't reach the nested type or when
   * the user wants to point at a specific {@code BRIDGE} constant. Mirrors the runtime {@link
   * io.github.eschizoid.telescope.mapping.Mapping#via(
   * io.github.eschizoid.telescope.Telescope.Accessor,
   * io.github.eschizoid.telescope.Telescope.Accessor,
   * io.github.eschizoid.telescope.conversion.Mapper) Mapping.via(srcAcc, tgtAcc, mapper)} factory.
   *
   * <pre>{@code
   * @Bridge(value = OrderEntity.class, viaMappers = {
   *   @ViaMapper(field = "address", using = AddressBridge.class)
   * })
   * public record Order(String id, Address address) {}
   * }</pre>
   */
  ViaMapper[] viaMappers() default {};

  /**
   * Override for the POJO construction strategy when emitting the target's rebuild block. Records
   * always use the canonical constructor and ignore this setting. Default {@link
   * WriteStrategy#AUTO} runs the priority ladder (name-matched ctor → static builder() → no-arg +
   * setters); the other values force one specific strategy and surface a precise compile error when
   * the POJO doesn't expose the required shape. Mirrors the runtime {@code WriteHint.writeBean(cls,
   * strategy)} hint.
   */
  WriteStrategy writeStrategy() default WriteStrategy.AUTO;

  /**
   * Skip the strict-bijection check. When {@code lenient = true}, the processor emits writes only
   * for the components named in {@link #renames()} / {@link #transforms()} plus same-name
   * auto-matches that exist on both sides; unmatched target components take their JLS default (zero
   * for primitives, empty for collections, {@code null} for references); unmatched source
   * components are silently ignored.
   *
   * <p>Designed for the small-DTO → large-entity pattern (e.g. mapping a 7-field DTO into a
   * 135-field entity whose 128 unmatched slots should stay at default). Without {@code lenient},
   * each of those 128 slots would need an explicit {@link #drops()} or {@link Constant @Constant}
   * entry to satisfy the bijection.
   *
   * <p><b>Round-trip-loss warning, by direction name.</b> {@code lenient = true} produces a
   * <em>partial-Iso</em>. The forward direction {@code BRIDGE.read(source)} is fine — unmatched
   * Target fields take JLS defaults, which is the whole point. The backward direction {@code
   * BRIDGE.set(source, target)} is the lossy one: every {@code Source}-side field that has no
   * {@code Target} counterpart comes back populated at the JLS default ({@code null} for
   * references, zero / empty for primitives and collections), regardless of what the original
   * Source held. Adopters who rely on backward round-trip safety must NOT set {@code lenient}. The
   * generated {@code <X>Bridge} class javadoc carries a matching warning so the asymmetry is
   * unambiguous in IDE auto-complete.
   *
   * <p>Same-name auto-matches and declared renames still go through their normal type-safety
   * pipeline — {@code lenient} only removes the bijection-completeness check, never the per-pair
   * type checks.
   */
  boolean lenient() default false;
}
