package io.github.eschizoid.telescope.annotations;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * An explicit nested-bridge override for one source field at {@link Bridge} codegen time. Mirrors
 * the runtime {@link io.github.eschizoid.telescope.mapping.Mapping#via(
 * io.github.eschizoid.telescope.Telescope.Accessor,
 * io.github.eschizoid.telescope.Telescope.Accessor,
 * io.github.eschizoid.telescope.conversion.Mapper) Mapping.via(srcAcc, tgtAcc, mapper)} factory —
 * the escape hatch for fields whose nested type-pair the auto-recursion can't handle, or where the
 * user wants to point at a specific {@code BRIDGE} constant instead of letting the processor emit
 * a fresh sub-bridge.
 *
 * <pre>{@code
 * @Bridge(value = OrderEntity.class, viaMappers = {
 *   @ViaMapper(field = "address", using = AddressBridge.class)
 * })
 * public record Order(String id, Address address) {}
 * }</pre>
 *
 * <p>The referenced bridge class must expose {@code public static T forward(S)} and {@code public
 * static S backward(T)} <em>static</em> methods whose argument and return types match the field's
 * source/target types — that is, the same shape any {@code <X>Bridge} class generated by {@link
 * Bridge} on the nested type pair would have. The processor inserts {@code Class.forward(...)} /
 * {@code Class.backward(...)} call sites into the generated bridge body for this field; if the
 * signatures don't match, {@code javac} catches the mismatch at the generated code, not here.
 *
 * <p><b>Not a {@code BridgeFn} instance.</b> Unlike {@link Transform#using()} which takes a {@link
 * io.github.eschizoid.telescope.conversion.BridgeFn} class that the processor <em>instantiates</em>
 * with a no-arg constructor and dispatches as {@code __tx_field.forward(...)} (instance method),
 * {@code @ViaMapper} expects a class with <em>static</em> methods and emits a direct {@code
 * Class.forward(...)} call. Pointing at a {@code BridgeFn} class here would produce a compile
 * error in the generated bridge body — the static-call shape doesn't match the instance-method
 * signature.
 *
 * <h2>When to use</h2>
 *
 * <ul>
 *   <li>The nested type is opaque to the processor (e.g. a third-party value class that doesn't
 *       carry {@code @Bridge} / {@code @Focus} and isn't a record).
 *   <li>The user wants two parents of the same nested pair to share one cached bridge constant
 *       rather than each emitting their own sub-bridge.
 *   <li>The nested pair already has a hand-rolled bridge under a non-default name and the user
 *       wants the parent to reference it explicitly.
 * </ul>
 *
 * <p>A field listed in {@code viaMappers} cannot also appear in {@link Bridge#drops()} or
 * {@link Bridge#defaults()} for the same pair — pick one mechanism per field.
 */
@Retention(RetentionPolicy.SOURCE)
public @interface ViaMapper {
  /**
   * Source field name whose conversion routes through {@link #using()}. Must name a real field on
   * the {@link Bridge} source.
   */
  String field();

  /**
   * The bridge class to delegate to. Must expose {@code public static T forward(S)} and
   * {@code public static S backward(T)} whose signatures match the field's source/target types.
   */
  Class<?> using();
}
