package org.telescope.codegen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;

/**
 * Annotation processor for {@link org.telescope.annotations.BeanFocus} — the bean analog of {@code
 * FocusProcessor}. For each annotated POJO it emits a sibling {@code <Pojo>Focus} class with a
 * {@code public static final Telescope<Pojo, PropType>} constant per readable property, each built
 * from {@code Telescope.lens(Pojo::getX, rebuild)} using only public members (no runtime
 * reflection).
 *
 * <p>The lens setter rebuilds the POJO with one property changed via a strategy auto-detected at
 * compile time, in priority order: a static {@code builder()} (with a per-property method {@code x}
 * / {@code setX} / {@code withX} and {@code build()}), then a public no-arg constructor plus {@code
 * setX} setters. Field injection is unavailable to generated code, so a POJO exposing neither is a
 * compile error (use {@code @Bridge} with a record, or runtime {@code Telescope.ofBean}).
 *
 * <p>Guards (each a compile error on the offending element): the annotated element must be a
 * top-level {@code class} (records use {@code @Focus}); it must have at least one readable
 * property; and a usable rebuild strategy must exist.
 */
@SupportedAnnotationTypes("org.telescope.annotations.BeanFocus")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class BeanFocusProcessor extends AbstractTelescopeProcessor {

  private record Prop(String name, String getter, TypeMirror type) {}

  @Override
  public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
    final var anno = processingEnv.getElementUtils().getTypeElement("org.telescope.annotations.BeanFocus");
    if (anno == null) return false;
    for (final var element : roundEnv.getElementsAnnotatedWith(anno)) {
      if (element.getKind() != ElementKind.CLASS) {
        error(element, "@BeanFocus is only supported on classes (records use @Focus)");
        continue;
      }
      if (element.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
        error(element, "@BeanFocus is only supported on top-level classes");
        continue;
      }
      generate((TypeElement) element);
    }
    return true;
  }

  private void generate(final TypeElement pojo) {
    final var elements = processingEnv.getElementUtils();
    final var pkg = elements.getPackageOf(pojo).getQualifiedName().toString();
    final var pojoName = pojo.getSimpleName().toString();
    final var focusName = pojoName + "Focus";
    final var qualifiedFocus = pkg.isEmpty() ? focusName : pkg + "." + focusName;

    final var props = properties(pojo);
    if (props.isEmpty()) {
      error(pojo, "@BeanFocus: " + pojo.getQualifiedName() + " has no readable properties (getX()/isX())");
      return;
    }

    // Resolve the rebuild strategy once, then a setter expression per property.
    final var builder = staticNoArgMethod(pojo, "builder");
    final var builderType =
      builder != null && builder.getReturnType().getKind() == TypeKind.DECLARED
        ? (TypeElement) ((DeclaredType) builder.getReturnType()).asElement()
        : null;
    final var useBuilder = builderType != null && hasBuild(builderType);
    if (!useBuilder && !hasPublicNoArgConstructor(pojo)) {
      error(
        pojo,
        "@BeanFocus: " +
          pojo.getQualifiedName() +
          " needs a static builder() or a public no-arg constructor with setters (field injection " +
          "isn't available to generated code — use @Bridge with a record, or Telescope.ofBean)"
      );
      return;
    }

    final var setters = new String[props.size()];
    for (var i = 0; i < props.size(); i++) {
      final var s = useBuilder
        ? builderSetter(builderType, props.get(i).name())
        : setterName(pojo, props.get(i).name());
      if (s == null) {
        error(
          pojo,
          "@BeanFocus: no " +
            (useBuilder ? "builder method" : "setter") +
            " for property '" +
            props.get(i).name() +
            "' on " +
            (useBuilder ? builderType.getQualifiedName() : pojo.getQualifiedName())
        );
        return;
      }
      setters[i] = s;
    }

    writeClass(
      qualifiedFocus,
      focusName,
      "Generated by telescope-codegen for @BeanFocus POJO " + pojoName + ".",
      pojo,
      out -> {
        for (var i = 0; i < props.size(); i++) {
          final var p = props.get(i);
          out.println(
            "  public static final Telescope<" + pojoName + ", " + boxedType(p.type()) + "> " + p.name() + " ="
          );
          out.println(
            "    Telescope.lens(" +
              pojoName +
              "::" +
              p.getter() +
              ", " +
              rebuild(p, props, setters, useBuilder, pojoName) +
              ");"
          );
          out.println();
          // Compile-time traversal for a collection property (List/Set/Iterable, Map values, or
          // Optional): descend into its elements with the element type baked in (reflection-free,
          // generator-proven).
          final var element = traversalElement(p.type());
          if (element != null) {
            out.println(
              "  public static final Telescope<" + pojoName + ", " + element + "> each" + capitalize(p.name()) + " ="
            );
            out.println("    " + p.name() + ".<" + element + ">each();");
            out.println();
          }
        }
      }
    );
  }

  // The lens setter: rebuild the POJO with property `target` set to v, all others read from p.
  private static String rebuild(
    final Prop target,
    final List<Prop> all,
    final String[] setters,
    final boolean useBuilder,
    final String pojoName
  ) {
    if (useBuilder) {
      final var sb = new StringBuilder("(p, v) -> " + pojoName + ".builder()");
      for (var i = 0; i < all.size(); i++) {
        final var arg = all.get(i).name().equals(target.name()) ? "v" : "p." + all.get(i).getter() + "()";
        sb.append(".").append(setters[i]).append("(").append(arg).append(")");
      }
      return sb.append(".build()").toString();
    }
    final var sb = new StringBuilder("(p, v) -> { final var c = new " + pojoName + "(); ");
    for (var i = 0; i < all.size(); i++) {
      final var arg = all.get(i).name().equals(target.name()) ? "v" : "p." + all.get(i).getter() + "()";
      sb.append("c.").append(setters[i]).append("(").append(arg).append("); ");
    }
    return sb.append("return c; }").toString();
  }

  private List<Prop> properties(final TypeElement pojo) {
    final Map<String, Prop> byName = new LinkedHashMap<>();
    for (final var m : ElementFilter.methodsIn(processingEnv.getElementUtils().getAllMembers(pojo))) {
      if (!isPublicInstance(m) || !m.getParameters().isEmpty() || m.getReturnType().getKind() == TypeKind.VOID) {
        continue;
      }
      final var name = m.getSimpleName().toString();
      final String prop;
      if (name.length() > 3 && name.startsWith("get")) {
        prop = decapitalize(name.substring(3));
      } else if (
        name.length() > 2 &&
        name.startsWith("is") &&
        (m.getReturnType().getKind() == TypeKind.BOOLEAN || "java.lang.Boolean".equals(m.getReturnType().toString()))
      ) {
        prop = decapitalize(name.substring(2));
      } else {
        continue;
      }
      if (!"class".equals(prop)) byName.putIfAbsent(prop, new Prop(prop, name, m.getReturnType()));
    }
    return new ArrayList<>(byName.values());
  }

  private boolean hasBuild(final TypeElement builderType) {
    for (final var m : ElementFilter.methodsIn(processingEnv.getElementUtils().getAllMembers(builderType))) {
      if (isPublicInstance(m) && m.getParameters().isEmpty() && m.getSimpleName().contentEquals("build")) return true;
    }
    return false;
  }
}
