package org.telescope.codegen;

import java.util.List;
import java.util.Set;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;

/**
 * Annotation processor for {@link org.telescope.annotations.BeanBridge}. For each annotated record,
 * emits a sibling class {@code <RecordName>Bridge} holding a {@code public static final
 * Telescope<Pojo, Record> BRIDGE} constant built from the public {@code
 * Telescope.from(Pojo.class).to(Record.class).using(forward, backward)} factory.
 *
 * <p>The two lambdas it emits call public members directly, so the runtime path uses no reflection
 * (and no {@code java.desktop}):
 *
 * <ul>
 *   <li><b>forward</b> (POJO &rarr; record): {@code new Record(p.getC1(), p.getC2(), ...)}, reading
 *       each component's public getter ({@code getX}, or {@code isX} for booleans);
 *   <li><b>backward</b> (record &rarr; POJO): reconstructs the POJO via one of three strategies,
 *       auto-detected at compile time in priority order:
 *       <ol>
 *         <li>a public all-args constructor (parameters in record-component order);
 *         <li>a static {@code builder()} whose builder exposes a per-component method ({@code x},
 *             {@code setX}, or {@code withX}) and {@code build()};
 *         <li>a public no-arg constructor plus a {@code setX} setter per component.
 *       </ol>
 * </ul>
 *
 * <p>A missing getter, setter, constructor, or builder method is a compile error here rather than a
 * runtime failure. Guards (each reported as a compile error on the offending element):
 *
 * <ul>
 *   <li>the annotated element must be a {@code record};
 *   <li>the record must be top-level — a nested record is rejected because the generated top-level
 *       {@code *Bridge} class cannot name a nested record's canonical constructor;
 *   <li>the {@code @BeanBridge} value must be a class type.
 * </ul>
 *
 * <p>{@link org.telescope.Telescope#fromBean(Class)} is the runtime, reflection-based equivalent.
 */
@SupportedAnnotationTypes("org.telescope.annotations.BeanBridge")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class BeanBridgeProcessor extends AbstractTelescopeProcessor {

  @Override
  public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
    final var anno = processingEnv.getElementUtils().getTypeElement("org.telescope.annotations.BeanBridge");
    if (anno == null) return false;
    for (final var element : roundEnv.getElementsAnnotatedWith(anno)) {
      if (element.getKind() != ElementKind.RECORD) {
        error(element, "@BeanBridge is only supported on records");
        continue;
      }
      if (element.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
        error(element, "@BeanBridge is only supported on top-level records");
        continue;
      }
      final var pojo = pojoType(element);
      if (pojo == null || pojo.getKind() != TypeKind.DECLARED) {
        error(element, "@BeanBridge value must be a class type");
        continue;
      }
      generate((TypeElement) element, (TypeElement) ((DeclaredType) pojo).asElement());
    }
    return true;
  }

  private void generate(final TypeElement record, final TypeElement pojo) {
    final var elements = processingEnv.getElementUtils();
    final var pkg = elements.getPackageOf(record).getQualifiedName().toString();
    final var recordName = record.getSimpleName().toString();
    final var bridgeName = recordName + "Bridge";
    final var qualifiedBridge = pkg.isEmpty() ? bridgeName : pkg + "." + bridgeName;
    final var pojoFq = pojo.getQualifiedName().toString();
    final List<? extends RecordComponentElement> components = record.getRecordComponents();

    final var forward = forwardExpr(record, pojo, recordName, components);
    if (forward == null) return;
    final var backward = backwardExpr(record, pojoFq, pojo, components);
    if (backward == null) return;

    writeClass(
      qualifiedBridge,
      bridgeName,
      "Generated by telescope-codegen for @BeanBridge record " + recordName + ".",
      record,
      out -> {
        out.println("  public static final Telescope<" + pojoFq + ", " + recordName + "> BRIDGE =");
        out.println("    Telescope.from(" + pojoFq + ".class).to(" + recordName + ".class).using(");
        out.println("      " + forward + ",");
        out.println("      " + backward + ");");
      }
    );
  }

  // POJO -> record: new Record(p.getC1(), p.getC2(), ...)
  private String forwardExpr(
    final TypeElement record,
    final TypeElement pojo,
    final String recordName,
    final List<? extends RecordComponentElement> components
  ) {
    final var sb = new StringBuilder("p -> new " + recordName + "(");
    for (var i = 0; i < components.size(); i++) {
      final var comp = components.get(i);
      final var getter = getterName(pojo, comp.getSimpleName().toString(), comp.asType());
      if (getter == null) {
        error(
          record,
          "@BeanBridge: " +
            pojo.getQualifiedName() +
            " has no getter for record component '" +
            comp.getSimpleName() +
            "'"
        );
        return null;
      }
      if (i > 0) sb.append(", ");
      sb.append("p.").append(getter).append("()");
    }
    return sb.append(")").toString();
  }

  // record -> POJO: auto-detect strategy (all-args ctor -> builder -> no-arg ctor + setters).
  private String backwardExpr(
    final TypeElement record,
    final String pojoFq,
    final TypeElement pojo,
    final List<? extends RecordComponentElement> components
  ) {
    final var n = components.size();

    for (final var ctor : ElementFilter.constructorsIn(pojo.getEnclosedElements())) {
      if (ctor.getModifiers().contains(Modifier.PUBLIC) && ctor.getParameters().size() == n) {
        final var sb = new StringBuilder("r -> new " + pojoFq + "(");
        appendAccessors(sb, components);
        return sb.append(")").toString();
      }
    }

    final var builder = staticNoArgMethod(pojo, "builder");
    if (builder != null && builder.getReturnType().getKind() == TypeKind.DECLARED) {
      final var builderType = (TypeElement) ((DeclaredType) builder.getReturnType()).asElement();
      final var sb = new StringBuilder("r -> " + pojoFq + ".builder()");
      for (final var comp : components) {
        final var setter = builderSetter(builderType, comp.getSimpleName().toString());
        if (setter == null) {
          error(
            record,
            "@BeanBridge: builder " +
              builderType.getQualifiedName() +
              " has no method for '" +
              comp.getSimpleName() +
              "'"
          );
          return null;
        }
        sb.append(".").append(setter).append("(r.").append(comp.getSimpleName()).append("())");
      }
      return sb.append(".build()").toString();
    }

    if (hasPublicNoArgConstructor(pojo)) {
      final var setters = new String[n];
      for (var i = 0; i < n; i++) {
        final var setter = setterName(pojo, components.get(i).getSimpleName().toString());
        if (setter == null) {
          error(
            record,
            "@BeanBridge: " +
              pojoFq +
              " has a no-arg constructor but no setter for '" +
              components.get(i).getSimpleName() +
              "'"
          );
          return null;
        }
        setters[i] = setter;
      }
      final var sb = new StringBuilder("r -> { final var p = new " + pojoFq + "(); ");
      for (var i = 0; i < n; i++) {
        sb.append("p.").append(setters[i]).append("(r.").append(components.get(i).getSimpleName()).append("()); ");
      }
      return sb.append("return p; }").toString();
    }

    error(
      record,
      "@BeanBridge: " +
        pojoFq +
        " has no usable construction strategy — needs an all-args " +
        "constructor (in record-component order), a static builder(), or a no-arg constructor with setters"
    );
    return null;
  }

  private static void appendAccessors(final StringBuilder sb, final List<? extends RecordComponentElement> comps) {
    for (var i = 0; i < comps.size(); i++) {
      if (i > 0) sb.append(", ");
      sb.append("r.").append(comps.get(i).getSimpleName()).append("()");
    }
  }

  private String getterName(final TypeElement pojo, final String comp, final TypeMirror type) {
    final var cap = capitalize(comp);
    final var isBoolean = type.getKind() == TypeKind.BOOLEAN || "java.lang.Boolean".equals(type.toString());
    for (final var m : ElementFilter.methodsIn(processingEnv.getElementUtils().getAllMembers(pojo))) {
      if (!isPublicInstance(m) || !m.getParameters().isEmpty() || m.getReturnType().getKind() == TypeKind.VOID) {
        continue;
      }
      final var name = m.getSimpleName().toString();
      if (name.equals("get" + cap) || (isBoolean && name.equals("is" + cap))) return name;
    }
    return null;
  }

  private TypeMirror pojoType(final Element element) {
    for (final var am : element.getAnnotationMirrors()) {
      if (
        !"org.telescope.annotations.BeanBridge".contentEquals(
          ((TypeElement) am.getAnnotationType().asElement()).getQualifiedName()
        )
      ) {
        continue;
      }
      for (final var entry : am.getElementValues().entrySet()) {
        if (entry.getKey().getSimpleName().contentEquals("value")) {
          return (TypeMirror) entry.getValue().getValue();
        }
      }
    }
    return null;
  }
}
