package org.telescope.codegen;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.NestingKind;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;

/**
 * Annotation processor for {@link org.telescope.annotations.Bridge}. For each annotated source type
 * (a record or a class), emits a sibling {@code <Source>Bridge} holding a {@code public static
 * final Telescope<Source, Target> BRIDGE}, where {@code Target} is the annotation's {@code
 * value()}.
 *
 * <p>Both sides may be records or POJOs. Each direction reads the opposite side's fields (a record
 * component {@code x()}, or a POJO getter {@code getX()} / {@code isX()}) and rebuilds the near
 * side by an auto-detected strategy: a record via its canonical constructor; a POJO via a public
 * constructor whose parameter names match the fields, then a static {@code builder()}, then a
 * no-arg constructor plus {@code setX} setters. Fields match by name and must form a bijection.
 *
 * <p>Guards (each a compile error): the source must be a top-level record/class; the target must be
 * a top-level record/class; and the two must expose the same field names with a usable strategy.
 */
@SupportedAnnotationTypes("org.telescope.annotations.Bridge")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class BridgeProcessor extends AbstractTelescopeProcessor {

  private static final String ANNOTATION = "org.telescope.annotations.Bridge";

  // A named field on either side: a record component or a POJO getter-property, with its type.
  private record Field(String name, TypeMirror type) {}

  @Override
  public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
    final var anno = processingEnv.getElementUtils().getTypeElement(ANNOTATION);
    if (anno == null) return false;
    for (final var element : roundEnv.getElementsAnnotatedWith(anno)) {
      if (element.getKind() != ElementKind.RECORD && element.getKind() != ElementKind.CLASS) {
        error(element, "@Bridge is only supported on records and classes");
        continue;
      }
      if (element.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
        error(element, "@Bridge is only supported on top-level types");
        continue;
      }
      final var target = targetType(element);
      if (target == null || target.getKind() != TypeKind.DECLARED) {
        error(element, "@Bridge value must be a class or record type");
        continue;
      }
      final var targetEl = (TypeElement) ((DeclaredType) target).asElement();
      if (targetEl.getNestingKind() != NestingKind.TOP_LEVEL) {
        error(element, "@Bridge target must be a top-level type");
        continue;
      }
      generate((TypeElement) element, targetEl);
    }
    return true;
  }

  private void generate(final TypeElement source, final TypeElement target) {
    final var pkg = processingEnv.getElementUtils().getPackageOf(source).getQualifiedName().toString();
    final var bridgeName = source.getSimpleName() + "Bridge";
    final var qualifiedBridge = pkg.isEmpty() ? bridgeName : pkg + "." + bridgeName;
    final var sourceFq = source.getQualifiedName().toString();
    final var targetFq = target.getQualifiedName().toString();

    final var sourceFields = fieldsOf(source);
    final var targetFields = fieldsOf(target);
    if (!sameNames(source, sourceFields, target, targetFields)) return;

    // forward: source -> target ; backward: target -> source.
    final var forward = direction(source, "s", sourceFields, target, targetFields);
    if (forward == null) return;
    final var backward = direction(target, "t", targetFields, source, sourceFields);
    if (backward == null) return;

    writeClass(
      qualifiedBridge,
      bridgeName.toString(),
      "Generated by telescope-codegen for @Bridge " + source.getSimpleName() + ".",
      source,
      out -> {
        out.println("  public static final Telescope<" + sourceFq + ", " + targetFq + "> BRIDGE =");
        out.println("    Telescope.from(" + sourceFq + ".class).to(" + targetFq + ".class).using(");
        out.println("      " + forward + ",");
        out.println("      " + backward + ");");
      }
    );
  }

  // A lambda `fromVar -> <build `to` reading each field from `from`>`, or null if `to` has no
  // usable
  // construction strategy (the error is reported on `to`'s annotated source).
  private String direction(
    final TypeElement from,
    final String fromVar,
    final List<Field> fromFields,
    final TypeElement to,
    final List<Field> toFields
  ) {
    final Function<String, String> read = name -> readExpr(from, fromVar, fieldByName(fromFields, name));
    final var body = buildExpr(to, read, toFields);
    return body == null ? null : fromVar + " -> " + body;
  }

  // Read field `f` from `var`: `var.f()` for a record, `var.getF()` / `var.isF()` for a POJO.
  private String readExpr(final TypeElement owner, final String var, final Field f) {
    if (owner.getKind() == ElementKind.RECORD) return var + "." + f.name() + "()";
    return var + "." + getterName(owner, f.name(), f.type()) + "()";
  }

  // Construct `to` from a name->expression reader: canonical ctor (record), or name-matched ctor /
  // builder / no-arg+setters (POJO). Returns an expression or a `{ ... return x; }` block; null on
  // failure (error reported on `to`).
  private String buildExpr(final TypeElement to, final Function<String, String> read, final List<Field> toFields) {
    final var toFq = to.getQualifiedName().toString();
    if (to.getKind() == ElementKind.RECORD) {
      final var args = to
        .getRecordComponents()
        .stream()
        .map(c -> read.apply(c.getSimpleName().toString()))
        .collect(Collectors.joining(", "));
      return "new " + toFq + "(" + args + ")";
    }

    // POJO: a public constructor whose parameter names match the fields (order-independent).
    for (final var ctor : ElementFilter.constructorsIn(to.getEnclosedElements())) {
      if (!ctor.getModifiers().contains(Modifier.PUBLIC) || ctor.getParameters().size() != toFields.size()) continue;
      final var args = new ArrayList<String>();
      var matched = true;
      for (final var p : ctor.getParameters()) {
        final var pn = p.getSimpleName().toString();
        if (!hasField(toFields, pn)) {
          matched = false;
          break;
        }
        args.add(read.apply(pn));
      }
      if (matched) return "new " + toFq + "(" + String.join(", ", args) + ")";
    }

    // POJO: a static builder() with a method per field.
    final var builder = staticNoArgMethod(to, "builder");
    if (builder != null && builder.getReturnType().getKind() == TypeKind.DECLARED) {
      final var builderType = (TypeElement) ((DeclaredType) builder.getReturnType()).asElement();
      final var sb = new StringBuilder(toFq + ".builder()");
      for (final var f : toFields) {
        final var method = builderSetter(builderType, f.name());
        if (method == null) {
          error(to, "@Bridge: builder " + builderType.getQualifiedName() + " has no method for '" + f.name() + "'");
          return null;
        }
        sb.append(".").append(method).append("(").append(read.apply(f.name())).append(")");
      }
      return sb.append(".build()").toString();
    }

    // POJO: a no-arg constructor plus a setter per field.
    if (hasPublicNoArgConstructor(to)) {
      final var sb = new StringBuilder("{ final var out = new " + toFq + "(); ");
      for (final var f : toFields) {
        final var setter = setterName(to, f.name());
        if (setter == null) {
          error(to, "@Bridge: " + toFq + " has a no-arg constructor but no setter for '" + f.name() + "'");
          return null;
        }
        sb.append("out.").append(setter).append("(").append(read.apply(f.name())).append("); ");
      }
      return sb.append("return out; }").toString();
    }

    error(
      to,
      "@Bridge: " +
        toFq +
        " has no usable construction strategy — needs a record canonical constructor, a constructor " +
        "whose parameter names match the fields, a static builder(), or a no-arg constructor with setters"
    );
    return null;
  }

  // The named fields of a type: record components, or POJO getter-properties (getX/isX), in order.
  private List<Field> fieldsOf(final TypeElement type) {
    if (type.getKind() == ElementKind.RECORD) {
      return type
        .getRecordComponents()
        .stream()
        .map(c -> new Field(c.getSimpleName().toString(), c.asType()))
        .toList();
    }
    final var byName = new LinkedHashMap<String, Field>();
    for (final var m : ElementFilter.methodsIn(processingEnv.getElementUtils().getAllMembers(type))) {
      if (!isPublicInstance(m) || !m.getParameters().isEmpty() || m.getReturnType().getKind() == TypeKind.VOID) {
        continue;
      }
      final var name = m.getSimpleName().toString();
      final String prop;
      if (name.length() > 3 && name.startsWith("get")) {
        prop = decapitalize(name.substring(3));
      } else if (
        name.length() > 2 &&
        name.startsWith("is") &&
        (m.getReturnType().getKind() == TypeKind.BOOLEAN || "java.lang.Boolean".equals(m.getReturnType().toString()))
      ) {
        prop = decapitalize(name.substring(2));
      } else {
        continue;
      }
      if (!"class".equals(prop)) byName.putIfAbsent(prop, new Field(prop, m.getReturnType()));
    }
    return List.copyOf(byName.values());
  }

  private String getterName(final TypeElement pojo, final String field, final TypeMirror type) {
    final var cap = capitalize(field);
    final var isBoolean = type.getKind() == TypeKind.BOOLEAN || "java.lang.Boolean".equals(type.toString());
    for (final var m : ElementFilter.methodsIn(processingEnv.getElementUtils().getAllMembers(pojo))) {
      if (!isPublicInstance(m) || !m.getParameters().isEmpty() || m.getReturnType().getKind() == TypeKind.VOID) {
        continue;
      }
      final var name = m.getSimpleName().toString();
      if (name.equals("get" + cap) || (isBoolean && name.equals("is" + cap))) return name;
    }
    return null;
  }

  private boolean sameNames(
    final TypeElement source,
    final List<Field> sourceFields,
    final TypeElement target,
    final List<Field> targetFields
  ) {
    final var sn = sourceFields.stream().map(Field::name).collect(Collectors.toCollection(java.util.TreeSet::new));
    final var tn = targetFields.stream().map(Field::name).collect(Collectors.toCollection(java.util.TreeSet::new));
    if (sn.equals(tn)) return true;
    error(
      source,
      "@Bridge: " +
        source.getSimpleName() +
        " and " +
        target.getSimpleName() +
        " must expose the same field names (a bijection). " +
        source.getSimpleName() +
        " has " +
        sn +
        ", " +
        target.getSimpleName() +
        " has " +
        tn
    );
    return false;
  }

  private static Field fieldByName(final List<Field> fields, final String name) {
    for (final var f : fields) if (f.name().equals(name)) return f;
    throw new IllegalStateException("no field '" + name + "' (bijection should have guaranteed it)");
  }

  private static boolean hasField(final List<Field> fields, final String name) {
    for (final var f : fields) if (f.name().equals(name)) return true;
    return false;
  }

  private TypeMirror targetType(final Element element) {
    for (final var am : element.getAnnotationMirrors()) {
      if (!ANNOTATION.contentEquals(((TypeElement) am.getAnnotationType().asElement()).getQualifiedName())) continue;
      for (final var entry : am.getElementValues().entrySet()) {
        if (entry.getKey().getSimpleName().contentEquals("value")) {
          return (TypeMirror) entry.getValue().getValue();
        }
      }
    }
    return null;
  }
}
