package org.telescope.codegen;

import java.io.PrintWriter;
import java.util.List;
import java.util.Set;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.TypeElement;

/**
 * Annotation processor for {@link org.telescope.annotations.Focus}. For each annotated record,
 * emits a fluent typed path navigator: a sibling class {@code <Record>Path<R>} whose methods
 * descend into the record's components, plus one container-step class per collection-shaped
 * component. The navigator gives the reading flow of the reflective DSL —
 *
 * <pre>{@code
 * CompanyPath.start().departments().each().teams().each().users().each().email()
 * }</pre>
 *
 * with end-to-end compile-time type checking, and the method bodies use {@link
 * org.telescope.Telescope#lens(java.util.function.Function, java.util.function.BiFunction)} plus
 * the no-arg {@code .each()} only — fully reflection-free.
 *
 * <p>Each scalar component emits a terminal {@code Telescope<R, T>} method; each sub-record
 * component emits a {@code <Sub>Path<R>}-returning method (the sub-record must also be annotated
 * with {@code @Focus}); each container component (List/Set/Iterable, Map values, Optional) emits a
 * container step whose {@code each} / {@code eachValue} / {@code whenPresent} method returns the
 * element's {@code Path} (if it's a record) or a terminal {@code Telescope<R, E>}.
 *
 * <p>Guards (each reported as a compile error on the offending element):
 *
 * <ul>
 *   <li>the annotated element must be a {@code record};
 *   <li>the record must be top-level — a nested record is rejected because the generated top-level
 *       {@code *Path} class cannot name a nested record's canonical constructor.
 * </ul>
 */
@SupportedAnnotationTypes("org.telescope.annotations.Focus")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class FocusProcessor extends AbstractTelescopeProcessor {

  @Override
  public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
    for (final Element element : roundEnv.getElementsAnnotatedWith(
      processingEnv.getElementUtils().getTypeElement("org.telescope.annotations.Focus")
    )) {
      if (element.getKind() != ElementKind.RECORD) {
        error(element, "@Focus is only supported on records");
        continue;
      }
      if (element.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
        error(
          element,
          "@Focus is only supported on top-level records (the generated *Path class can't " +
            "reference a nested record's canonical constructor)"
        );
        continue;
      }
      generate((TypeElement) element);
    }
    return true;
  }

  private void generate(final TypeElement recordType) {
    final var pkg = processingEnv.getElementUtils().getPackageOf(recordType).getQualifiedName().toString();
    final var recordName = recordType.getSimpleName().toString();
    final var pathName = recordName + "Path";
    final var qualifiedPath = pkg.isEmpty() ? pathName : pkg + "." + pathName;
    final List<? extends RecordComponentElement> components = recordType.getRecordComponents();

    // First, emit one container-step class per collection-shaped component (each goes in its own
    // top-level source file because each is public and Java permits at most one public top-level
    // type per file).
    for (final var comp : components) {
      final var shape = traversalKind(comp.asType());
      if (shape != null) emitStep(recordType, recordName, pkg, comp, shape);
    }

    // Then emit the main Path navigator.
    writeInstanceClass(
      qualifiedPath,
      pathName,
      "<R>",
      "Generated by telescope-codegen for @Focus record " + recordName + ".",
      recordType,
      out -> {
        out.println("  private final Telescope<R, " + recordName + "> path;");
        out.println();
        out.println("  " + pathName + "(final Telescope<R, " + recordName + "> path) { this.path = path; }");
        out.println();
        out.println(
          "  public static " +
            pathName +
            "<" +
            recordName +
            "> start() { return new " +
            pathName +
            "<>(Telescope.of(" +
            recordName +
            ".class)); }"
        );
        out.println();
        out.println("  public Telescope<R, " + recordName + "> get() { return path; }");
        out.println();
        for (final var comp : components) emitComponentMethod(out, recordName, components, comp);
        emitTelescopeForwarders(out, "path", recordName);
      }
    );
  }

  // Emits one navigator method for the given record component, dispatching on its shape:
  // container (List/Set/Iterable, Map, Optional) -> per-component step class; sub-record ->
  // <Sub>Path<R>; scalar -> terminal Telescope<R, T>.
  private void emitComponentMethod(
    final PrintWriter out,
    final String recordName,
    final List<? extends RecordComponentElement> components,
    final RecordComponentElement comp
  ) {
    final var compName = comp.getSimpleName().toString();
    final var compType = comp.asType();
    final var setter = canonicalSetter(recordName, components, compName);
    final var shape = traversalKind(compType);
    if (shape != null) {
      final var stepName = recordName + capitalize(compName) + "Step";
      out.println("  public " + stepName + "<R> " + compName + "() {");
      out.println(
        "    return new " +
          stepName +
          "<>(path.then(Telescope.lens(" +
          recordName +
          "::" +
          compName +
          ", " +
          setter +
          ")));"
      );
      out.println("  }");
      out.println();
      return;
    }
    final var subFq = navigableType(compType, ElementKind.RECORD, "org.telescope.annotations.Focus");
    if (subFq != null) {
      out.println("  public " + subFq + "Path<R> " + compName + "() {");
      out.println(
        "    return new " +
          subFq +
          "Path<>(path.then(Telescope.lens(" +
          recordName +
          "::" +
          compName +
          ", " +
          setter +
          ")));"
      );
      out.println("  }");
      out.println();
      return;
    }
    final var typeStr = shortenStdImports(boxedType(compType));
    out.println("  public Telescope<R, " + typeStr + "> " + compName + "() {");
    out.println("    return path.then(Telescope.lens(" + recordName + "::" + compName + ", " + setter + "));");
    out.println("  }");
    out.println();
  }

  // Emits a container-step class for one collection-shaped component (List/Set/Iterable, Map, or
  // Optional). Step is shaped as Telescope<R, ContainerType> and exposes get() plus the matching
  // step method (each / eachValue / whenPresent), which returns the element's <X>Path when the
  // element is a record or a terminal Telescope<R, Element> otherwise.
  private void emitStep(
    final TypeElement recordType,
    final String recordName,
    final String pkg,
    final RecordComponentElement comp,
    final TraversalShape shape
  ) {
    final var compName = comp.getSimpleName().toString();
    final var stepName = recordName + capitalize(compName) + "Step";
    final var qualifiedStep = pkg.isEmpty() ? stepName : pkg + "." + stepName;
    final var containerType = shortenStdImports(comp.asType().toString());
    final var rawElementType = shape.elementType();
    final var elementType = shortenStdImports(rawElementType);
    final var stepMethod = shape.stepMethod();
    final var elementIsNavigable = isFocusAnnotatedRecord(rawElementType);
    final var elementResultType = elementIsNavigable ? elementType + "Path<R>" : "Telescope<R, " + elementType + ">";
    final var elementBody = elementIsNavigable
      ? "new " + elementType + "Path<>(path.<" + elementType + ">each())"
      : "path.<" + elementType + ">each()";

    writeInstanceClass(
      qualifiedStep,
      stepName,
      "<R>",
      "Generated by telescope-codegen for @Focus container hop " + recordName + "." + compName + ".",
      recordType,
      out -> {
        out.println("  private final Telescope<R, " + containerType + "> path;");
        out.println();
        out.println("  " + stepName + "(final Telescope<R, " + containerType + "> path) { this.path = path; }");
        out.println();
        out.println("  public Telescope<R, " + containerType + "> get() { return path; }");
        out.println();
        out.println("  public " + elementResultType + " " + stepMethod + "() {");
        out.println("    return " + elementBody + ";");
        out.println("  }");
        out.println();
        emitTelescopeForwarders(out, "path", containerType);
      }
    );
  }

  // Whether the type's qualified name names a record that itself carries @Focus — i.e. has its own
  // generated *Path<R>. Used to decide a container step's element-result shape.
  private boolean isFocusAnnotatedRecord(final String qualifiedName) {
    final var elements = processingEnv.getElementUtils();
    final var element = elements.getTypeElement(qualifiedName);
    if (element == null || element.getKind() != ElementKind.RECORD) return false;
    final var anno = elements.getTypeElement("org.telescope.annotations.Focus");
    if (anno == null) return false;
    for (final var am : element.getAnnotationMirrors()) {
      if (am.getAnnotationType().asElement().equals(anno)) return true;
    }
    return false;
  }

  // The canonical-constructor setter expression for a target component: (s, v) -> new Record(args)
  // where each arg is `v` for the target component or `s.other()` for the others.
  private static String canonicalSetter(
    final String recordName,
    final List<? extends RecordComponentElement> components,
    final String targetName
  ) {
    final var sb = new StringBuilder("(s, v) -> new " + recordName + "(");
    for (var i = 0; i < components.size(); i++) {
      final var name = components.get(i).getSimpleName().toString();
      sb.append(name.equals(targetName) ? "v" : "s." + name + "()");
      if (i < components.size() - 1) sb.append(", ");
    }
    return sb.append(")").toString();
  }
}
