package org.telescope.codegen;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;

/**
 * Annotation processor for {@link org.telescope.annotations.Focus}. For each annotated record,
 * emits a sibling class {@code <RecordName>Focus} with one {@code public static final
 * Telescope<Record, FieldType>} constant per record component. Each constant is built via {@link
 * org.telescope.Telescope#lens(java.util.function.Function, java.util.function.BiFunction)} — the
 * getter is the component accessor and the setter is a canonical-constructor call with the targeted
 * component swapped for the new value — so the runtime path is reflection-free and the field-name
 * reference is resolved at compile time.
 *
 * <p>Primitive component types are boxed to their wrappers (see {@link #boxedType}) because the
 * {@code Telescope} type parameter cannot be a primitive.
 *
 * <p>Guards (each reported as a compile error on the offending element):
 *
 * <ul>
 *   <li>the annotated element must be a {@code record};
 *   <li>the record must be top-level — a nested record is rejected because the generated top-level
 *       {@code *Focus} class cannot name a nested record's canonical constructor.
 * </ul>
 *
 * <p>Without this processor on the build's annotation-processor path, {@code @Focus} is inert and
 * the reflection-based {@code .field(Record::component)} path still works.
 */
@SupportedAnnotationTypes("org.telescope.annotations.Focus")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class FocusProcessor extends AbstractProcessor {

  @Override
  public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
    for (final Element element : roundEnv.getElementsAnnotatedWith(
      processingEnv.getElementUtils().getTypeElement("org.telescope.annotations.Focus")
    )) {
      if (element.getKind() != ElementKind.RECORD) {
        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, "@Focus is only supported on records", element);
        continue;
      }
      if (element.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
        processingEnv
          .getMessager()
          .printMessage(
            Diagnostic.Kind.ERROR,
            "@Focus is only supported on top-level records (the generated *Focus class can't " +
              "reference a nested record's canonical constructor)",
            element
          );
        continue;
      }
      generateFocus((TypeElement) element);
    }
    return true;
  }

  private void generateFocus(final TypeElement recordType) {
    final var pkg = processingEnv.getElementUtils().getPackageOf(recordType).getQualifiedName().toString();
    final var recordName = recordType.getSimpleName().toString();
    final var focusName = recordName + "Focus";
    final var qualifiedFocus = pkg.isEmpty() ? focusName : pkg + "." + focusName;
    final List<? extends RecordComponentElement> components = recordType.getRecordComponents();

    try {
      final var file = processingEnv.getFiler().createSourceFile(qualifiedFocus, recordType);
      try (final var out = new PrintWriter(file.openWriter())) {
        if (!pkg.isEmpty()) {
          out.println("package " + pkg + ";");
          out.println();
        }
        out.println("import org.telescope.Telescope;");
        out.println();
        out.println("/** Generated by telescope-codegen for @Focus record " + recordName + ". */");
        out.println("public final class " + focusName + " {");
        out.println();
        out.println("  private " + focusName + "() {}");
        out.println();
        for (final var comp : components) {
          final var fieldName = comp.getSimpleName().toString();
          final var fieldType = boxedType(comp.asType());
          out.println("  public static final Telescope<" + recordName + ", " + fieldType + "> " + fieldName + " =");
          out.print("    Telescope.lens(" + recordName + "::" + fieldName + ", (s, v) -> new " + recordName + "(");
          for (int i = 0; i < components.size(); i++) {
            final var cName = components.get(i).getSimpleName().toString();
            out.print(cName.equals(fieldName) ? "v" : "s." + cName + "()");
            if (i < components.size() - 1) out.print(", ");
          }
          out.println("));");
          out.println();
        }
        out.println("}");
      }
    } catch (final IOException e) {
      processingEnv
        .getMessager()
        .printMessage(Diagnostic.Kind.ERROR, "Failed to write " + qualifiedFocus + ": " + e.getMessage(), recordType);
    }
  }

  /**
   * The generated field type must be a reference type (the Telescope type parameter can't be a
   * primitive). Box primitives to their wrappers; pass other types through untouched.
   */
  private static String boxedType(final TypeMirror type) {
    return switch (type.getKind()) {
      case BOOLEAN -> "Boolean";
      case BYTE -> "Byte";
      case SHORT -> "Short";
      case INT -> "Integer";
      case LONG -> "Long";
      case CHAR -> "Character";
      case FLOAT -> "Float";
      case DOUBLE -> "Double";
      default -> type.toString();
    };
  }
}
