package org.telescope.codegen;

import java.util.List;
import java.util.Set;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.TypeElement;

/**
 * Annotation processor for {@link org.telescope.annotations.Focus}. For each annotated record,
 * emits a sibling class {@code <RecordName>Focus} with one {@code public static final
 * Telescope<Record, FieldType>} constant per record component. Each constant is built via {@link
 * org.telescope.Telescope#lens(java.util.function.Function, java.util.function.BiFunction)} — the
 * getter is the component accessor and the setter is a canonical-constructor call with the targeted
 * component swapped for the new value — so the runtime path is reflection-free and the field-name
 * reference is resolved at compile time.
 *
 * <p>Primitive component types are boxed to their wrappers (see {@link
 * AbstractTelescopeProcessor#boxedType}) because the {@code Telescope} type parameter cannot be a
 * primitive.
 *
 * <p>Guards (each reported as a compile error on the offending element):
 *
 * <ul>
 *   <li>the annotated element must be a {@code record};
 *   <li>the record must be top-level — a nested record is rejected because the generated top-level
 *       {@code *Focus} class cannot name a nested record's canonical constructor.
 * </ul>
 *
 * <p>Without this processor on the build's annotation-processor path, {@code @Focus} is inert and
 * the reflection-based {@code .field(Record::component)} path still works.
 */
@SupportedAnnotationTypes("org.telescope.annotations.Focus")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class FocusProcessor extends AbstractTelescopeProcessor {

  @Override
  public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
    for (final Element element : roundEnv.getElementsAnnotatedWith(
      processingEnv.getElementUtils().getTypeElement("org.telescope.annotations.Focus")
    )) {
      if (element.getKind() != ElementKind.RECORD) {
        error(element, "@Focus is only supported on records");
        continue;
      }
      if (element.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
        error(
          element,
          "@Focus is only supported on top-level records (the generated *Focus class can't " +
            "reference a nested record's canonical constructor)"
        );
        continue;
      }
      generateFocus((TypeElement) element);
    }
    return true;
  }

  private void generateFocus(final TypeElement recordType) {
    final var pkg = processingEnv.getElementUtils().getPackageOf(recordType).getQualifiedName().toString();
    final var recordName = recordType.getSimpleName().toString();
    final var focusName = recordName + "Focus";
    final var qualifiedFocus = pkg.isEmpty() ? focusName : pkg + "." + focusName;
    final List<? extends RecordComponentElement> components = recordType.getRecordComponents();

    writeClass(
      qualifiedFocus,
      focusName,
      "Generated by telescope-codegen for @Focus record " + recordName + ".",
      recordType,
      out -> {
        for (final var comp : components) {
          final var fieldName = comp.getSimpleName().toString();
          final var fieldType = boxedType(comp.asType());
          out.println("  public static final Telescope<" + recordName + ", " + fieldType + "> " + fieldName + " =");
          out.print("    Telescope.lens(" + recordName + "::" + fieldName + ", (s, v) -> new " + recordName + "(");
          for (int i = 0; i < components.size(); i++) {
            final var cName = components.get(i).getSimpleName().toString();
            out.print(cName.equals(fieldName) ? "v" : "s." + cName + "()");
            if (i < components.size() - 1) out.print(", ");
          }
          out.println("));");
          out.println();
          // Compile-time traversal: for a collection component, a constant that descends into its
          // elements with the element type baked in (reflection-free, generator-proven).
          final var element = iterableElement(comp.asType());
          if (element != null) {
            out.println(
              "  public static final Telescope<" + recordName + ", " + element + "> each" + capitalize(fieldName) + " ="
            );
            out.println("    " + fieldName + ".<" + element + ">each();");
            out.println();
          }
        }
      }
    );
  }
}
