package io.github.eschizoid.telescope.internal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.eschizoid.telescope.Telescope;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Tests {@link MetadataHolderProbe} — the {@link ClassValue}-cached runtime probe that
 * short-circuits the reflective dispatch sites in {@link Telescope} when a sibling {@code
 * <X>FieldOptics} metadata holder is present.
 *
 * <p>The top-level fixture {@link ProbedRecord} carries {@code @Focus}, so {@code FocusProcessor}
 * generates a sibling {@code ProbedRecordTelescope} holder during test compilation. The "no holder"
 * cases use {@link UnannotatedRecord}, which has no annotation and therefore no holder.
 */
class MetadataHolderProbeTest {

  @Test
  @DisplayName("probeFor returns a HolderRef when <X>FieldOptics sits next to X on the classpath")
  void probeFindsHolder() {
    final var maybeHolder = MetadataHolderProbe.probeFor(ProbedRecord.class);
    assertTrue(
      maybeHolder.isPresent(),
      "expected to find ProbedRecordTelescope on the classpath (generated by FocusProcessor); " +
        "is the @Focus processor wired into testAnnotationProcessor?"
    );
    final var holder = maybeHolder.get();
    assertEquals(
      ProbedRecord.class.getName() + "FieldOptics",
      holder.holderClass().getName(),
      "holder class name should be <X>FieldOptics in the same package as X"
    );
    // FocusProcessor emits one Telescope<ProbedRecord, FieldType> constant per record component.
    assertEquals(2, holder.constantsByName().size(), "expected one constant per record component");
    assertTrue(holder.constantsByName().containsKey("name"), "constant 'name' should be present");
    assertTrue(holder.constantsByName().containsKey("age"), "constant 'age' should be present");
  }

  @Test
  @DisplayName("probeFor returns Optional.empty for a class with no sibling <X>FieldOptics holder")
  void probeReturnsEmptyForUnannotatedClass() {
    final var maybeHolder = MetadataHolderProbe.probeFor(UnannotatedRecord.class);
    assertTrue(maybeHolder.isEmpty(), "expected no holder for an unannotated record; got " + maybeHolder);
  }

  @Test
  @DisplayName("probeFor is cached: repeated calls return the same Optional instance (ClassValue memoised)")
  void probeIsCached() {
    final var first = MetadataHolderProbe.probeFor(ProbedRecord.class);
    final var second = MetadataHolderProbe.probeFor(ProbedRecord.class);
    assertSame(first, second, "ClassValue should memoise the Optional<HolderRef>");

    // Absent case is also cached.
    final var firstEmpty = MetadataHolderProbe.probeFor(UnannotatedRecord.class);
    final var secondEmpty = MetadataHolderProbe.probeFor(UnannotatedRecord.class);
    assertSame(firstEmpty, secondEmpty, "ClassValue should also memoise the Optional.empty() probe miss");
  }

  @Test
  @DisplayName("HolderRef.constantsByName exposes the raw codegen-emitted Telescope constants as Object")
  void constantsByNameExposesRawTelescopeConstants() {
    // :internal can't see Telescope, so the holder's constants are typed as Object. The :core
    // caller (Telescope#singleHolderLens / #holderReadersFor) does the cast to recover the
    // underlying Lens — keeping the cast on the side of the module boundary that owns the type.
    final var maybeHolder = MetadataHolderProbe.probeFor(ProbedRecord.class);
    assertNotNull(maybeHolder.orElse(null), "holder should be discovered for a class with a sibling <X>FieldOptics");
    final var holder = maybeHolder.get();
    assertNotNull(holder.constantsByName().get("name"), "'name' must be present in the holder's constant map");
    assertNotNull(holder.constantsByName().get("age"), "'age' must be present in the holder's constant map");
    assertNull(holder.constantsByName().get("nonExistentField"), "unknown names should map to null");
  }

  @Test
  @DisplayName("probeFor returns Optional.empty() for an unannotated class — no <X>FieldOptics sibling")
  void probeForReturnsEmptyForUnannotatedClass() {
    final var result = MetadataHolderProbe.probeFor(UnannotatedRecord.class);
    assertTrue(result.isEmpty(), "absent holder should produce Optional.empty() so the dispatch site can fall through");
  }
}
