package io.github.eschizoid.telescope.internal;

import io.github.eschizoid.telescope.internal.MetadataHolderProbe;
import io.github.eschizoid.telescope.internal.Reflective;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.github.eschizoid.telescope.Telescope;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Tests {@link MetadataHolderProbe} — the {@link ClassValue}-cached runtime probe that
 * short-circuits the reflective dispatch sites in {@link Telescope} when a sibling {@code
 * <X>Telescope} metadata holder is present.
 *
 * <p>The top-level fixture {@link ProbedRecord} carries {@code @Focus}, so {@code FocusProcessor}
 * generates a sibling {@code ProbedRecordTelescope} holder during test compilation. The "no holder"
 * cases use {@link UnannotatedRecord}, which has no annotation and therefore no holder.
 */
class MetadataHolderProbeTest {

  @Test
  @DisplayName("probeFor returns a HolderRef when <X>Telescope sits next to X on the classpath")
  void probeFindsHolder() {
    final var maybeHolder = MetadataHolderProbe.probeFor(ProbedRecord.class);
    assertTrue(
      maybeHolder.isPresent(),
      "expected to find ProbedRecordTelescope on the classpath (generated by FocusProcessor); " +
        "is the @Focus processor wired into testAnnotationProcessor?"
    );
    final var holder = maybeHolder.get();
    assertEquals(
      ProbedRecord.class.getName() + "Telescope",
      holder.holderClass().getName(),
      "holder class name should be <X>Telescope in the same package as X"
    );
    // FocusProcessor emits one Telescope<ProbedRecord, FieldType> constant per record component.
    assertEquals(2, holder.constantsByName().size(), "expected one constant per record component");
    assertTrue(holder.constantsByName().containsKey("name"), "constant 'name' should be present");
    assertTrue(holder.constantsByName().containsKey("age"), "constant 'age' should be present");
  }

  @Test
  @DisplayName("probeFor returns Optional.empty for a class with no sibling <X>Telescope holder")
  void probeReturnsEmptyForUnannotatedClass() {
    final var maybeHolder = MetadataHolderProbe.probeFor(UnannotatedRecord.class);
    assertTrue(maybeHolder.isEmpty(), "expected no holder for an unannotated record; got " + maybeHolder);
  }

  @Test
  @DisplayName("probeFor is cached: repeated calls return the same Optional instance (ClassValue memoised)")
  void probeIsCached() {
    final var first = MetadataHolderProbe.probeFor(ProbedRecord.class);
    final var second = MetadataHolderProbe.probeFor(ProbedRecord.class);
    assertSame(first, second, "ClassValue should memoise the Optional<HolderRef>");

    // Absent case is also cached.
    final var firstEmpty = MetadataHolderProbe.probeFor(UnannotatedRecord.class);
    final var secondEmpty = MetadataHolderProbe.probeFor(UnannotatedRecord.class);
    assertSame(firstEmpty, secondEmpty, "ClassValue should also memoise the Optional.empty() probe miss");
  }

  @Test
  @DisplayName("lensFromHolder returns null when no <X>Telescope sibling is on the classpath")
  void lensFromHolderReturnsNullWhenAbsent() {
    final var result = MetadataHolderProbe.lensFromHolder(UnannotatedRecord.class, "name");
    assertNull(result, "absent holder should produce a null Lens so dispatch can fall through");
  }

  @Test
  @DisplayName("lensFromHolder returns the holder's pre-baked Lens when name matches a constant")
  void lensFromHolderReturnsConstantWhenPresent() {
    final var lens = MetadataHolderProbe.<ProbedRecord, String>lensFromHolder(ProbedRecord.class, "name");
    assertNotNull(lens, "holder is present and 'name' is a known constant — expected a non-null Lens");
    final var rec = new ProbedRecord("alice", 30);
    assertEquals("alice", lens.get(rec), "the holder's lens should read 'name' identically to the record accessor");
    final var renamed = lens.set(rec, "bob");
    assertEquals("bob", renamed.name(), "the holder's lens setter should rebuild the record with the new value");
    assertEquals(30, renamed.age(), "other components should be carried over unchanged");
  }

  @Test
  @DisplayName("holder present but name missing throws IllegalStateException with a precise diagnostic")
  void holderPresentNameMissingThrows() {
    final var thrown = assertThrows(
      IllegalStateException.class,
      () -> MetadataHolderProbe.lensFromHolder(ProbedRecord.class, "nonExistentField"),
      "silent fallback would mask stale codegen — a known-holder name miss must throw"
    );
    final var msg = thrown.getMessage();
    assertTrue(msg.contains("nonExistentField"), "diagnostic should name the missing component, got: " + msg);
    assertTrue(msg.contains("ProbedRecord"), "diagnostic should name the source class, got: " + msg);
    assertTrue(
      msg.contains("Re-run the @Focus") || msg.contains("@BeanFocus"),
      "diagnostic should point the user at the codegen step, got: " + msg
    );
  }
}
