package io.github.eschizoid.telescope.codegen;

import java.io.PrintWriter;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.RecordComponentElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;

/**
 * Annotation processor for {@link io.github.eschizoid.telescope.annotations.Focus}. For each
 * annotated record, emits a fluent typed path navigator: a sibling class {@code <Record>Path<R>}
 * whose methods descend into the record's components, plus one container-step class per
 * collection-shaped component. The navigator gives the reading flow of the reflective DSL —
 *
 * <pre>{@code
 * CompanyPath.start().departments().each().teams().each().users().each().email()
 * }</pre>
 *
 * with end-to-end compile-time type checking, and the method bodies use {@link
 * io.github.eschizoid.telescope.Telescope#lens(java.util.function.Function,
 * java.util.function.BiFunction)} plus the no-arg {@code .each()} only — fully reflection-free.
 *
 * <p>Each scalar component emits a terminal {@code Telescope<R, T>} method; each sub-record
 * component emits a {@code <Sub>Path<R>}-returning method (the sub-record must also be annotated
 * with {@code @Focus}); each container component (List/Set/Iterable, Map values, Optional) emits a
 * container step whose {@code each} / {@code eachValue} / {@code whenPresent} method returns the
 * element's {@code Path} (if it's a record) or a terminal {@code Telescope<R, E>}.
 *
 * <p>Guards (each reported as a compile error on the offending element):
 *
 * <ul>
 *   <li>the annotated element must be a {@code record};
 *   <li>the record must be top-level — a nested record is rejected because the generated top-level
 *       {@code *Path} class cannot name a nested record's canonical constructor.
 * </ul>
 */
@SupportedAnnotationTypes("io.github.eschizoid.telescope.annotations.Focus")
@SupportedSourceVersion(SourceVersion.RELEASE_25)
public final class FocusProcessor extends AbstractTelescopeProcessor {

  /**
   * Public no-arg constructor required by the {@link javax.annotation.processing.Processor} SPI.
   */
  public FocusProcessor() {
    super();
  }

  @Override
  public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
    for (final Element element : roundEnv.getElementsAnnotatedWith(
      processingEnv.getElementUtils().getTypeElement("io.github.eschizoid.telescope.annotations.Focus")
    )) {
      if (element.getKind() != ElementKind.RECORD) {
        error(element, "@Focus is only supported on records");
        continue;
      }
      if (element.getEnclosingElement().getKind() != ElementKind.PACKAGE) {
        error(
          element,
          "@Focus is only supported on top-level records (the generated *Path class can't " +
            "reference a nested record's canonical constructor)"
        );
        continue;
      }
      generate((TypeElement) element);
    }
    return true;
  }

  private void generate(final TypeElement recordType) {
    final var pkg = processingEnv.getElementUtils().getPackageOf(recordType).getQualifiedName().toString();
    final var recordName = recordType.getSimpleName().toString();
    final var pathName = recordName + "Path";
    final var qualifiedPath = pkg.isEmpty() ? pathName : pkg + "." + pathName;
    final List<? extends RecordComponentElement> components = recordType.getRecordComponents();

    // First, emit one container-step class per collection-shaped component (each goes in its own
    // top-level source file because each is public and Java permits at most one public top-level
    // type per file).
    for (final var comp : components) {
      final var shape = traversalKind(comp.asType());
      if (shape != null) emitStep(recordType, recordName, pkg, comp, shape);
    }

    // Then emit the main Path navigator.
    writeInstanceClass(
      qualifiedPath,
      pathName,
      "<R>",
      "Generated by telescope-codegen for @Focus record " + recordName + ".",
      recordType,
      out -> {
        emitPathClassHeader(out, pathName, recordName);
        for (final var comp : components) emitComponentMethod(out, recordName, components, comp);
        final var bridgeTarget = bridgeTargetFqn(recordType);
        if (bridgeTarget != null) emitBridgeHop(out, recordName, bridgeTarget);
        emitTelescopeForwarders(out, recordName);
      }
    );

    // Finally, emit the sibling <X>Telescope metadata holder (ADR-0006). Pure additive: nothing
    // consumes the constants yet (Phase B wires the runtime probe in a separate PR). If any
    // component carries an un-emittable type (wildcards, type-vars, etc.), we report a compile
    // error and skip the holder emission for that record only.
    emitMetadataHolder(recordType, recordName, pkg, components);
  }

  // Emits the sibling <X>Telescope holder, one `public static final Telescope<X, FieldType>`
  // constant per record component. Containers are emitted as raw container lenses (Telescope<X,
  // List<E>>, etc.) — the consumer composes via .then(...) to descend. See ADR-0006 §2.
  private void emitMetadataHolder(
    final TypeElement recordType,
    final String recordName,
    final String pkg,
    final List<? extends RecordComponentElement> components
  ) {
    final var holderName = recordName + "Telescope";
    final var qualifiedHolder = pkg.isEmpty() ? holderName : pkg + "." + holderName;

    // Reject up-front: any un-emittable component type kills the whole holder for this record
    // (the per-record holder is the unit of regeneration, mixed-quality holders would mask the
    // gap). The Path navigator is unaffected — it has its own type handling.
    for (final var comp : components) {
      if (!isEmittableAsTypedConstant(comp.asType())) {
        error(
          recordType,
          "@Focus: cannot emit metadata constant for component '" +
            comp.getSimpleName() +
            "' of type '" +
            comp.asType() +
            "' — generics with wildcard or self-referential bounds are not supported. Remove " +
            "@Focus from this record to use the runtime path."
        );
        return;
      }
    }

    final Set<String> extraImports = new LinkedHashSet<>();
    for (final var comp : components) collectStdImports(comp.asType(), extraImports);

    writeMetadataHolderClass(
      qualifiedHolder,
      holderName,
      "Generated by telescope-codegen for @Focus record " +
        recordName +
        ". Per-component Telescope constants for runtime hybrid dispatch (ADR-0006).",
      recordType,
      extraImports,
      out -> {
        for (final var comp : components) {
          final var compName = comp.getSimpleName().toString();
          final var fieldType = shortenStdImports(boxedType(comp.asType()));
          final var lensArgs = recordName + "::" + compName + ", " + canonicalSetter(recordName, components, compName);
          out.println(
            "  public static final Telescope<" +
              recordName +
              ", " +
              fieldType +
              "> " +
              compName +
              " = Telescope.lens(" +
              lensArgs +
              ");"
          );
          out.println();
        }
      }
    );
  }

  // Collect java.util.{List, Map, Optional, Set} imports needed for a component's typed-constant
  // type signature on the holder. Only standard names that `shortenStdImports` shortens need an
  // import; user-package types stay fully-qualified in the generated source.
  private static void collectStdImports(final TypeMirror type, final Set<String> imports) {
    final var raw = type.toString();
    if (raw.contains("java.util.List")) imports.add("java.util.List");
    if (raw.contains("java.util.Map")) imports.add("java.util.Map");
    if (raw.contains("java.util.Optional")) imports.add("java.util.Optional");
    if (raw.contains("java.util.Set")) imports.add("java.util.Set");
  }

  // Emits one navigator method for the given record component, dispatching on its shape:
  // container (List/Set/Iterable, Map, Optional) -> per-component step class; sub-record ->
  // <Sub>Path<R>; scalar -> terminal Telescope<R, T>.
  private void emitComponentMethod(
    final PrintWriter out,
    final String recordName,
    final List<? extends RecordComponentElement> components,
    final RecordComponentElement comp
  ) {
    final var compName = comp.getSimpleName().toString();
    final var lensArgs = recordName + "::" + compName + ", " + canonicalSetter(recordName, components, compName);
    emitNavigatorMethod(out, recordName, compName, comp.asType(), lensArgs, FOCUS_ONLY);
  }

  // Container-step emission for an @Focus record's collection-shaped component. All shared logic
  // (List/Set/Map/Optional dispatch, navigable-element check, body emission) lives in
  // AbstractTelescopeProcessor#emitContainerStep; this just supplies record-flavored inputs.
  private void emitStep(
    final TypeElement recordType,
    final String recordName,
    final String pkg,
    final RecordComponentElement comp,
    final TraversalShape shape
  ) {
    final var compName = comp.getSimpleName().toString();
    final var containerType = shortenStdImports(comp.asType().toString());
    emitContainerStep(
      recordType,
      recordName,
      pkg,
      compName,
      containerType,
      shape,
      FOCUS_ONLY,
      "Generated by telescope-codegen for @Focus container hop " + recordName + "." + compName + "."
    );
  }

  // The annotation set used by emitNavigatorMethod / emitContainerStep to decide whether a
  // sub-component's element type has its own generated <X>Path<R>.
  private static final Set<String> FOCUS_ONLY = Set.of("io.github.eschizoid.telescope.annotations.Focus");

  // The canonical-constructor setter expression for a target component: (s, v) -> new Record(args)
  // where each arg is `v` for the target component or `s.other()` for the others.
  private static String canonicalSetter(
    final String recordName,
    final List<? extends RecordComponentElement> components,
    final String targetName
  ) {
    final var sb = new StringBuilder("(s, v) -> new " + recordName + "(");
    for (var i = 0; i < components.size(); i++) {
      final var name = components.get(i).getSimpleName().toString();
      sb.append(name.equals(targetName) ? "v" : "s." + name + "()");
      if (i < components.size() - 1) sb.append(", ");
    }
    return sb.append(")").toString();
  }
}
