[versions]
junit = "6.1.3"
graphqlJava = "26.1"
spotless = "8.10.1"
googleJavaFormat = "1.30.0"
prettier = "3.8.1"
prettierPluginJava = "2.8.1"
testcontainers = "2.0.5"
slf4j = "2.0.18"
jmh = "0.7.3"
axion = "1.18.7"
jreleaser = "1.19.0"
jgit = "6.10.0.202406032230-r"
lombok = "1.18.46"

[libraries]
graphqlJava = { module = "com.graphql-java:graphql-java", version.ref = "graphqlJava" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainersJunit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
jgitGpgBc = { module = "org.eclipse.jgit:org.eclipse.jgit.gpg.bc", version.ref = "jgit" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
axion = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
